import { useQuery } from "@tanstack/react-query";
import { router, useLocalSearchParams } from "expo-router";
import * as Haptics from "expo-haptics";
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { PreviewButton } from "../../components/PreviewButton";
import { fetchBeat } from "../../lib/api";
import { useCart } from "../../lib/cart";
import { LICENSE_TIERS, formatPrice } from "../../lib/models";
export default function BeatDetail(){const {slug}=useLocalSearchParams<{slug:string}>();const {add}=useCart();const q=useQuery({queryKey:["beat",slug],queryFn:()=>fetchBeat(slug)});if(q.isLoading)return <View style={s.center}><ActivityIndicator color="#A855F7"/></View>;if(q.isError||!q.data)return <View style={s.center}><Text style={s.error}>This beat is unavailable.</Text></View>;const beat=q.data;return <ScrollView style={s.page} contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ BACK TO CATALOG</Text></Pressable><Image source={{uri:beat.artworkUrl}} style={s.art}/><View style={s.row}><View style={{flex:1}}><Text style={s.title}>{beat.title}</Text><Text style={s.meta}>{beat.genre} · {beat.bpm} BPM · {beat.musicalKey}</Text></View><PreviewButton uri={beat.audioUrl} beatId={beat.id} size={54}/></View><Text style={s.section}>Choose your rights</Text>{LICENSE_TIERS.filter(t=>t.id!=="exclusive"||!beat.soldExclusive).map(t=><Pressable key={t.id} style={s.tier} onPress={()=>{Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);add(beat,t.id);router.push("/(tabs)/cart")}}><View style={{flex:1}}><Text style={s.tierName}>{t.name}</Text><Text style={s.desc}>{t.description}</Text></View><View><Text style={s.price}>{formatPrice(t.priceCents)}</Text><Text style={s.add}>ADD</Text></View></Pressable>)}</ScrollView>};const s=StyleSheet.create({page:{flex:1,backgroundColor:"#0B0A11"},content:{padding:20,paddingBottom:40},center:{flex:1,backgroundColor:"#0B0A11",alignItems:"center",justifyContent:"center"},error:{color:"#fff"},back:{color:"#CDA8FF",fontWeight:"900",fontSize:11,letterSpacing:1},art:{width:"100%",aspectRatio:1,borderRadius:22,marginTop:16,backgroundColor:"#17141F"},row:{flexDirection:"row",gap:14,alignItems:"center",marginTop:18},title:{color:"#F8F6FB",fontSize:27,fontWeight:"900"},meta:{color:"#ABA6B5",fontSize:13,marginTop:5},section:{color:"#F8F6FB",fontSize:21,fontWeight:"900",marginTop:30,marginBottom:12},tier:{flexDirection:"row",gap:12,backgroundColor:"#17141F",borderRadius:16,padding:15,borderWidth:1,borderColor:"rgba(255,255,255,.08)",marginBottom:9},tierName:{color:"#F8F6FB",fontSize:15,fontWeight:"800"},desc:{color:"#9E98A8",fontSize:11,lineHeight:16,marginTop:4},price:{color:"#E9D9FF",fontSize:15,fontWeight:"900",textAlign:"right"},add:{color:"#CDA8FF",fontSize:10,fontWeight:"900",letterSpacing:.8,marginTop:9,textAlign:"right"}});
